### ISSUE TITLE
Format Labels in Excel

### ISSUE THREAD

**Issue by mirraseigerman** [pdcamilleri/WMIF#78]
The values corresponding to the presentation format type seem to be incorrect - for instance in the mirra_1 trial, all I observed was 10 samples of experience formated reviews but in the data file there are "1s" under: description; frequency random; distribution random; and simultaneous random (as well as the experience column). This doesn't match up.

**Comment by pdcamilleri** [comment]
Try testing again. Just tested myself now with a single simul format and the output was as expected. I think I fixed this a couple days ago.

Also note that if the "randomise" box is ticked on the admin page, even if the format is not shown, then a 1 will be under that heading.

E.g. if experience is not ticked, but experience is randomised, then there will be a 0 under "experience shown" but a 1 under "experience random" since these values are basically written to the CSV file straight from the admin page.

**Comment by mirraseigerman** [comment]
yep, i tried this. still having trouble. For the latest trial as mirra_2 I did the following:
 
I made sure only experience + random was selected for both products but the following data come out:

description_random = 1
frequency_random = 1
distribution_random = 1
simultaneous_random = 1

Note - experience_shown + experience_random were correctly presented in the output (i.e., as 1s)
