### ISSUE TITLE
Attention Check Questions

### ISSUE THREAD

**Issue by mirraseigerman** [pdcamilleri/WMIF#95]
No output data for these two questions.

**Comment by pdcamilleri** [comment]
Just ran a test

69,test15,1,...,0,1,,,
69,test15,1,...,0,0,,,
69,test15,1,...,0,0,,,
69,test15,1,...,0,0,1,1,

The data is there, its just on the last line, because the data for the attention check questions is not recorded until the end of the experiment, whereas the first 3 lines of the output file are created during the experiment.

So the data is there, being saved correctly, and I don't think this should block the experiment from being run.

Reopen this issue if this is not the case.
